export const REMOVE_ERROR = 'REMOVE_ERROR'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const ADD_ERROR = 'ADD_ERROR'
export const ADD_LOADING = 'ADD_LOADING'

export const SET_SALADS = 'SET_SALADS'
export const SET_CURRENT_SALAD = 'SET_CURRENT_SALAD'
export const SET_ORDER = 'SET_ORDER'
export const SET_COMPOSITIONS = 'SET_COMPOSITIONS'
